// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfTj7gNxbn40iea3_WTUNXpybTZrFk7Is',
    appId: '1:974970043330:web:75d71d2fcd28927ee7345b',
    messagingSenderId: '974970043330',
    projectId: 'firenote-422',
    authDomain: 'firenote-422.firebaseapp.com',
    storageBucket: 'firenote-422.firebasestorage.app',
    measurementId: 'G-PPWNL084SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfdcWAbgIDvlLTuXTHuQ0yT2yHu7cfyH8',
    appId: '1:974970043330:android:639c57d6a56b2a68e7345b',
    messagingSenderId: '974970043330',
    projectId: 'firenote-422',
    storageBucket: 'firenote-422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFEGPuL712rNUUSIhXw3Z4Ru8LeI7lflY',
    appId: '1:974970043330:ios:8ccfc717efd9f7cbe7345b',
    messagingSenderId: '974970043330',
    projectId: 'firenote-422',
    storageBucket: 'firenote-422.firebasestorage.app',
    iosBundleId: 'com.example.firebaseExp422',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFEGPuL712rNUUSIhXw3Z4Ru8LeI7lflY',
    appId: '1:974970043330:ios:8ccfc717efd9f7cbe7345b',
    messagingSenderId: '974970043330',
    projectId: 'firenote-422',
    storageBucket: 'firenote-422.firebasestorage.app',
    iosBundleId: 'com.example.firebaseExp422',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfTj7gNxbn40iea3_WTUNXpybTZrFk7Is',
    appId: '1:974970043330:web:462bebe1088ed7f2e7345b',
    messagingSenderId: '974970043330',
    projectId: 'firenote-422',
    authDomain: 'firenote-422.firebaseapp.com',
    storageBucket: 'firenote-422.firebasestorage.app',
    measurementId: 'G-6RQXF14L6Z',
  );
}
